In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [ ]:
# load data
url = 'https://raw.githubusercontent.com/anandafitri00/plancellsignalling/main/plantCellSignaling.csv'
data = pd.read_csv(url)
# data = data.drop(columns=['*'])
data

     ABA CLOSURE Ca CaATPase CAIM CIS  ... DEPOLAR HATPase KOUT  KAP Actin   NO
0      1       0  1        1    1   0  ...     0.0     1.0  1.0  0.0   0.0  1.0
1      1       1  0        0    0   0  ...     1.0     0.0  1.0  0.0   1.0  1.0
2      1       1  0        0    0   1  ...     1.0     0.0  1.0  0.0   1.0  0.0
3      1       1  0        0    0   0  ...     1.0     0.0  1.0  0.0   1.0  0.0
4      1       1  0        0    0   0  ...     1.0     0.0  1.0  0.0   1.0  0.0
...   ..     ... ..      ...  ...  ..  ...     ...     ...  ...  ...   ...  ...
5710   1       1  1        1    0   1  ...     1.0     0.0  1.0  0.0   1.0  1.0
5711   1       1  0        1    0   1  ...     1.0     0.0  1.0  0.0   1.0  1.0
5712   1       1  1        0    0   1  ...     1.0     0.0  1.0  0.0   1.0  1.0
5713   1       1  1        1    0   1  ...     1.0     0.0  1.0  0.0   1.0  1.0
5714   1       1  0        1    0   1  ...     1.0     0.0  1.0  0.0   1.0  1.0

[5715 rows x 43 columns]

In [ ]:
data = data.drop(data[data.ABA=="*"].index)

In [ ]:
# data = data.iloc[:1000]
data

     ABA CLOSURE Ca CaATPase CAIM CIS  ... DEPOLAR HATPase KOUT  KAP Actin   NO
0      1       0  1        1    1   0  ...     0.0     1.0  1.0  0.0   0.0  1.0
1      1       1  0        0    0   0  ...     1.0     0.0  1.0  0.0   1.0  1.0
2      1       1  0        0    0   1  ...     1.0     0.0  1.0  0.0   1.0  0.0
3      1       1  0        0    0   0  ...     1.0     0.0  1.0  0.0   1.0  0.0
4      1       1  0        0    0   0  ...     1.0     0.0  1.0  0.0   1.0  0.0
...   ..     ... ..      ...  ...  ..  ...     ...     ...  ...  ...   ...  ...
5710   1       1  1        1    0   1  ...     1.0     0.0  1.0  0.0   1.0  1.0
5711   1       1  0        1    0   1  ...     1.0     0.0  1.0  0.0   1.0  1.0
5712   1       1  1        0    0   1  ...     1.0     0.0  1.0  0.0   1.0  1.0
5713   1       1  1        1    0   1  ...     1.0     0.0  1.0  0.0   1.0  1.0
5714   1       1  0        1    0   1  ...     1.0     0.0  1.0  0.0   1.0  1.0

[5456 rows x 43 columns]

In [ ]:
# data.isnull().sum()

In [ ]:
atr = data.columns
for j in range(len(atr)):
  data[atr[j]] = pd.to_numeric(data[atr[j]])

data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5456 entries, 0 to 5714
Data columns (total 43 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ABA       5456 non-null   int64
 1   CLOSURE   5456 non-null   int64
 2   Ca        5456 non-null   int64
 3   CaATPase  5456 non-null   int64
 4   CAIM      5456 non-null   int64
 5   CIS       5456 non-null   int64
 6   ABH1      5456 non-null   int64
 7   GCR       5456 non-null   int64
 8   ERA1      5456 non-null   int64
 9   PEPC      5456 non-null   int64
 10  OST       5456 non-null   int64
 11  SPHK      5456 non-null   int64
 12  PH        5456 non-null   int64
 13  PLD       5456 non-null   int64
 14  ROP2      5456 non-null   int64
 15  KEV       5456 non-null   int64
 16  AGB       5456 non-null   int64
 17  RAC       5456 non-null   int64
 18  RCN       5456 non-null   int64
 19  NIA12     5456 non-null   int64
 20  PLC       5456 non-null   int64
 21  InsPK     5456 non-null   int64
 22  IP6       5456 non-null   int64
 23  ADPRc     5456 non-null   int64
 24  GC        5456 non-null   int64
 25  NOS       5456 non-null   int64
 26  S1P       5456 non-null   int64
 27  PA        5456 non-null   float64
 28  IP3       5456 non-null   float64
 29  cADPR     5456 non-null   float64
 30  cGMP      5456 non-null   float64
 31  MALATE    5456 non-null   float64
 32  ATRBOH    5456 non-null   float64
 33  GPA       5456 non-null   float64
 34  ROS       5456 non-null   float64
 35  AnionEM   5456 non-null   float64
 36  ABI       5456 non-null   float64
 37  DEPOLAR   5456 non-null   float64
 38  HATPase   5456 non-null   float64
 39  KOUT      5456 non-null   float64
 40  KAP       5456 non-null   float64
 41  Actin     5456 non-null   float64
 42  NO        5456 non-null   float64
dtypes: float64(16), int64(27)
memory usage: 1.8 MB

In [ ]:
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

data = data.applymap(encode_units)

In [ ]:
data = data.sample(n=1000)

In [ ]:
data.corr()

          ABA   CLOSURE        Ca  ...       KAP     Actin        NO
ABA       NaN       NaN       NaN  ...       NaN       NaN       NaN
CLOSURE   NaN  1.000000 -0.200274  ... -0.474792  0.400132 -0.170802
Ca        NaN -0.200274  1.000000  ...  0.132150 -0.058160  0.239483
CaATPase  NaN -0.168067  0.373522  ...  0.147618 -0.093747  0.425313
CAIM      NaN -0.480941  0.102615  ...  0.472504 -0.428577  0.044909
CIS       NaN -0.150469  0.477483  ...  0.055182 -0.083887  0.412016
ABH1      NaN  0.380028 -0.142324  ... -0.351462  0.369603 -0.119390
GCR       NaN  0.429687 -0.107562  ... -0.447930  0.483740 -0.100325
ERA1      NaN  0.348860 -0.133304  ... -0.386864  0.248517 -0.126485
PEPC      NaN -0.323706  0.098433  ...  0.457514 -0.397724  0.092624
OST       NaN  0.416033 -0.101934  ... -0.464032  0.300909 -0.080679
SPHK      NaN  0.401974 -0.080988  ... -0.390473  0.347307 -0.148427
PH        NaN  0.409057 -0.076792  ... -0.502571  0.306774 -0.113989
PLD       NaN  0.592216 -0.178899  ... -0.290279  0.224263 -0.192450
ROP2      NaN  0.598033 -0.246281  ... -0.306738  0.258007 -0.169662
KEV       NaN -0.198799  0.428738  ...  0.157137 -0.101284  0.369029
AGB       NaN       NaN       NaN  ...       NaN       NaN       NaN
RAC       NaN -0.387467  0.136709  ...  0.564201 -0.361777  0.052955
RCN       NaN  0.409057 -0.106441  ... -0.592315  0.408242 -0.128510
NIA12     NaN  0.419046 -0.087667  ... -0.466548  0.447285 -0.054543
PLC       NaN -0.218811  0.467870  ...  0.138693 -0.114553  0.467811
InsPK     NaN  0.394780 -0.116011  ... -0.553082  0.424304 -0.109009
IP6       NaN  0.419046 -0.100893  ... -0.279715  0.266223 -0.093410
ADPRc     NaN -0.176182  0.254527  ...  0.069539 -0.077195  0.556983
GC        NaN -0.247799  0.224734  ...  0.234777 -0.154354  0.545314
NOS       NaN -0.152924  0.454310  ...  0.065055 -0.041439  0.530919
S1P       NaN  0.425347 -0.102615  ... -0.240885  0.312187 -0.057402
PA        NaN  0.574010 -0.173781  ... -0.268480  0.181119 -0.135908
IP3       NaN -0.213939  0.289632  ...  0.158707 -0.087538  0.459159
cADPR     NaN -0.215545  0.307124  ...  0.190819 -0.148381  0.385809
cGMP      NaN -0.228622  0.343125  ...  0.118172 -0.079933  0.344668
MALATE    NaN -0.364745  0.038731  ...  0.501478 -0.424337  0.082219
ATRBOH    NaN  0.611624 -0.196910  ... -0.208163  0.174161 -0.174668
GPA       NaN  0.494604 -0.144482  ... -0.394182  0.257569 -0.102564
ROS       NaN  0.578495 -0.228528  ... -0.323568  0.253781 -0.134556
AnionEM   NaN  0.594368 -0.102829  ... -0.293198  0.191891 -0.083556
ABI       NaN -0.440172  0.187358  ...  0.283155 -0.120098  0.129409
DEPOLAR   NaN  0.468575 -0.097109  ... -0.617871  0.351410 -0.051245
HATPase   NaN -0.434698  0.095243  ...  0.508420 -0.399042  0.088025
KOUT      NaN  0.519145 -0.095375  ... -0.402798  0.467824 -0.075950
KAP       NaN -0.474792  0.132150  ...  1.000000 -0.522919  0.060676
Actin     NaN  0.400132 -0.058160  ... -0.522919  1.000000 -0.052095
NO        NaN -0.170802  0.239483  ...  0.060676 -0.052095  1.000000

[43 rows x 43 columns]

In [ ]:
del data['ABA']
del data['AGB']
del data['KAP']
del data['KOUT']
del data['HATPase']
del data['DEPOLAR']
del data['ABI']
del data['AnionEM']
del data['ROS']
del data['GPA']
del data['ATRBOH']
del data['MALATE']
del data['cGMP']
del data['cADPR']
del data['IP3']
del data['PA']
del data['S1P']
del data['NOS']
del data['GC']
del data['KEV']
del data['RAC']
del data['RCN']
del data['NIA12']
del data['PLC']
del data['InsPK']
del data['IP6']
del data['ADPRc']

In [ ]:
data.head()

      CLOSURE  Ca  CaATPase  CAIM  CIS  ABH1  ...  SPHK  PH  PLD  ROP2  Actin  NO
5396        1   0         0     0    0     1  ...     1   1    1     1      1   0
5436        0   0         0     0    0     1  ...     1   1    1     0      1   0
1841        1   0         0     0    0     1  ...     1   1    1     1      1   0
3576        1   0         0     0    0     1  ...     1   1    1     1      1   0
5576        1   0         0     0    0     1  ...     1   1    1     1      1   0

[5 rows x 16 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 5396 to 5187
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CLOSURE   1000 non-null   int64
 1   Ca        1000 non-null   int64
 2   CaATPase  1000 non-null   int64
 3   CAIM      1000 non-null   int64
 4   CIS       1000 non-null   int64
 5   ABH1      1000 non-null   int64
 6   GCR       1000 non-null   int64
 7   ERA1      1000 non-null   int64
 8   PEPC      1000 non-null   int64
 9   OST       1000 non-null   int64
 10  SPHK      1000 non-null   int64
 11  PH        1000 non-null   int64
 12  PLD       1000 non-null   int64
 13  ROP2      1000 non-null   int64
 14  Actin     1000 non-null   int64
 15  NO        1000 non-null   int64
dtypes: int64(16)
memory usage: 132.8 KB

In [ ]:
frequent_itemsets = apriori(data, min_support=0.07, use_colnames=True)

In [ ]:
frequent_itemsets.head()

   support    itemsets
0    0.844   (CLOSURE)
1    0.194        (Ca)
2    0.207  (CaATPase)
3    0.301       (CIS)
4    0.974      (ABH1)

In [ ]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules

        antecedents  ... conviction
0            (ABH1)  ...   1.168800
1         (CLOSURE)  ...        inf
2         (CLOSURE)  ...        inf
3             (GCR)  ...   1.226439
4            (ERA1)  ...   1.138567
...             ...  ...        ...
1229997      (ABH1)  ...   1.002975
1229998       (GCR)  ...   1.003806
1229999        (NO)  ...   1.540429
1230000       (CIS)  ...   1.289358
1230001        (PH)  ...   1.003448

[1230002 rows x 9 columns]

In [ ]:
rules.max()

antecedents                                                        (PH)
consequents           (ROP2, SPHK, PLD, Actin, OST, CLOSURE, ERA1, A...
antecedent support                                                0.978
consequent support                                                0.978
support                                                           0.962
confidence                                                            1
lift                                                             3.7857
leverage                                                       0.099718
conviction                                                          inf
dtype: object

In [ ]:
rules[ (rules['lift'] >= 1) & (rules['confidence'] >= 0.9)]

                      antecedents  ... conviction
1                       (CLOSURE)  ...        inf
2                       (CLOSURE)  ...        inf
5                       (CLOSURE)  ...        inf
6                       (CLOSURE)  ...        inf
9                       (CLOSURE)  ...        inf
...                           ...  ...        ...
1229691  (CIS, ERA1, CLOSURE, NO)  ...   2.738333
1229697  (ABH1, CLOSURE, CIS, NO)  ...   2.738333
1229700   (CIS, CLOSURE, GCR, NO)  ...   2.738333
1229703    (CIS, CLOSURE, PH, NO)  ...   2.738333
1229906        (CIS, CLOSURE, NO)  ...   2.738333

[328302 rows x 9 columns]